"""
scripts/export_final_tables.py — Tự động kết xuất 6 bảng chính thức của bài báo sang CSV và LaTeX booktabs.
Tuân thủ nghiêm ngặt AGENT_RULES §6, D18, D20, D54, D70, D78, D82, D91, D93, D95.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
import pandas as pd

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "results" / "tables" / "final"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def escape_latex(text: str) -> str:
    """Escape an toàn các ký tự đặc biệt trong LaTeX."""
    text = str(text)
    # Thứ tự thay thế quan trọng: escape backslash trước
    text = text.replace("\\", "\\textbackslash{}")
    text = text.replace("&", "\\&")
    text = text.replace("%", "\\%")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    text = text.replace("_", "\\_")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace("~", "\\textasciitilde{}")
    text = text.replace("^", "\\textasciicircum{}")
    return text

def write_table_pair(
    basename: str,
    caption: str,
    label: str,
    headers: list[str],
    rows: list[list[str]],
    col_align: str,
    df_raw: pd.DataFrame,
    notes: str = ""
) -> None:
    """Ghi song song tệp CSV sạch và tệp LaTeX booktabs."""
    # 1. Ghi CSV
    csv_path = OUTPUT_DIR / f"{basename}.csv"
    df_raw.to_csv(csv_path, index=False, encoding="utf-8")
    
    # 2. Ghi LaTeX
    tex_path = OUTPUT_DIR / f"{basename}.tex"
    lines = [
        "% Auto-generated by scripts/export_final_tables.py. Do not edit manually.",
        "\\begin{table*}[t]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\small",
        f"\\begin{{tabular}}{{{col_align}}}",
        "\\toprule"
    ]
    # Header
    escaped_headers = [f"\\textbf{{{h}}}" for h in headers]
    lines.append(" & ".join(escaped_headers) + " \\\\")
    lines.append("\\midrule")
    # Rows
    for row in rows:
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    if notes:
        lines.append("\\vskip 4pt")
        lines.append(f"\\parbox{{\\textwidth}}{{\\footnotesize \\textit{{Note:}} {notes}}}")
    lines.append("\\end{table*}")
    
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Exported: {csv_path.name} and {tex_path.name}")

# ==============================================================================
# 1. BẢNG 1: Phân hoạch Dữ liệu theo Drive & Tham số Hiệu dụng Máy ảnh
# ==============================================================================
def export_table_1():
    split_meta_path = REPO_ROOT / "splits" / "split_metadata.json"
    bct_report_path = REPO_ROOT / "results" / "tables" / "repartition_bct_report.json"
    
    with open(split_meta_path, "r", encoding="utf-8") as f:
        split_meta = json.load(f)
    with open(bct_report_path, "r", encoding="utf-8") as f:
        bct_report = json.load(f)
        
    splits = split_meta["splits"]
    roles = {
        "A": "Detector training & Camera calibration priors",
        "V": "Confidence threshold & Checkpoint selection (last.pt)",
        "B": "Residual model fitting & Geometry covariance fusion",
        "C": "Conformal quantile calibration (alpha = 0.10)",
        "T": "Final held-out evaluation (Single-run locked)"
    }
    
    manifest_path = REPO_ROOT / "results" / "final" / "numbers_manifest.json"
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    num = manifest.get("numbers", {})

    car_hard_counts = {
        "A": int(num.get("split_a_car_hard_count", {}).get("value", 11291)),
        "V": int(num.get("split_v_car_hard_count", {}).get("value", 611)),
        "B": int(num.get("split_b_car_hard_count", {}).get("value", 4776)),
        "C": int(num.get("split_c_car_hard_count", {}).get("value", 1826)),
        "T": int(num.get("split_t_car_hard_count", {}).get("value", 3212)),
    }
    car_drives = {
        "A": 18,
        "V": 6,
        "B": int(num.get("split_b_car_drives", {}).get("value", 12)),
        "C": int(num.get("split_c_car_drives", {}).get("value", 10)),
        "T": int(num.get("split_t_car_drives", {}).get("value", 10)),
    }
    top1_shares = {
        "A": "16.0\\%",
        "V": "41.0\\%",
        "B": f"{num.get('split_b_top1_share', {}).get('display_str', '26.8%').replace('%', '\\\\%')}",
        "C": f"{num.get('split_c_top1_share', {}).get('display_str', '28.7%').replace('%', '\\\\%')}",
        "T": f"{num.get('split_t_top1_share', {}).get('display_str', '23.3%').replace('%', '\\\\%')}",
    }
    neff_vals = {
        "A": "---",
        "V": "---",
        "B": str(num.get("split_b_neff", {}).get("display_str", "5.29")),
        "C": str(num.get("split_c_neff", {}).get("display_str", "5.28")),
        "T": str(num.get("split_t_neff", {}).get("display_str", "5.28")),
    }
    
    csv_rows = []
    latex_rows = []
    
    for s_name in ["A", "V", "B", "C", "T"]:
        s_info = splits[s_name]
        f_cnt = s_info.get("n_frames", s_info.get("frame_count", 0))
        d_cnt = s_info.get("n_drives", s_info.get("drive_count", 0))
        c_hard = car_hard_counts[s_name]
        c_drv = car_drives[s_name]
        t1 = top1_shares[s_name].replace("\\%", "%")
        neff = neff_vals[s_name]
        role = roles[s_name]
        
        csv_rows.append({
            "split": s_name,
            "frames": f_cnt,
            "drives_total": d_cnt,
            "drives_with_cars": c_drv,
            "car_hard_count": c_hard,
            "top1_drive_share": t1,
            "n_eff": neff,
            "role": role
        })
        
        latex_rows.append([
            f"Split {s_name}",
            f"{f_cnt:,}",
            str(d_cnt),
            str(c_drv),
            f"{c_hard:,}",
            top1_shares[s_name],
            neff,
            escape_latex(role)
        ])
        
    df_raw = pd.DataFrame(csv_rows)
    headers = ["Split", "Frames", "Total Drives", "Car Drives ($k$)", "Car Hard ($N_{\\text{gt}}$)", "Top-1 Share", "$n_{\\text{eff}}$", "Role in Study"]
    notes = "Dataset split follows drive-level disjoint partitioning (splits-v2, seed 85 simulated annealing). Effective camera priors estimated from Split A: $W_{\\text{eff}} = 2.6184\\text{ m}$, $H_{\\text{obj}} = 1.6797\\text{ m}$, $H_{\\text{cam}} = 2.0422\\text{ m}$, $\\delta = -4.6782\\text{ px}$. Split T is held-out and zero-touch locked."
    write_table_pair("tab_01_dataset_split", "Drive-based Dataset Partitioning and Physical Prior Setup (KITTI)", "tab:dataset_split", headers, latex_rows, "lrrrrrrl", df_raw, notes)

# ==============================================================================
# 2. BẢNG 2: Hiệu năng Cue Đơn lẻ, Hợp nhất & Ablation trên Split B OOF
# ==============================================================================
def export_table_2():
    res_b_path = REPO_ROOT / "results" / "tables" / "residual_oof_b.json"
    abl_b_path = REPO_ROOT / "results" / "tables" / "ablation_oof_b.json"
    
    with open(res_b_path, "r", encoding="utf-8") as f:
        res_b = json.load(f)
    with open(abl_b_path, "r", encoding="utf-8") as f:
        abl_b = json.load(f)
        
    csv_rows = []
    latex_rows = []
    
    # 1. Baseline comparisons on YOLO11s (res_b common_support)
    cs = res_b["yolo11s_640"]["common_support"]
    names_map = {
        "d": ("Fused Geometry $Z_d$ (d*)", cs["d"]["pooled"]),
        "e": ("Direct Depth $Z_e$ (e)", cs["e"]["pooled"]),
        "f0": ("Linear Residual $Z_{f0}$ (f0)", cs["f0"]["pooled"]),
        "f": ("Full Residual $\\hat{Z}_f$ (f)", cs["f"]["pooled"])
    }
    
    # Single cue baselines dynamically loaded from geometry_on_detector_bbox.json (Split B eval_split_B)
    geom_b_path = REPO_ROOT / "results" / "tables" / "geometry_on_detector_bbox.json"
    with open(geom_b_path, "r", encoding="utf-8") as f:
        geom_b_data = json.load(f)
    det_b = geom_b_data["detectors"]["yolo11s_640"]["eval_split_B"]
    
    single_cues = [
        ("Width Cue $Z_w$ (a)", det_b["a_zw_det"]),
        ("Height Cue $Z_h$ (b)", det_b["b_zh_det"]),
        ("Ground Cue $Z_g$ (c*)", det_b["c_zg_det"])
    ]
    for c_name, c_data in single_cues:
        p_abs = round(float(c_data["pooled_absrel"]), 4)
        m_abs = round(float(c_data["macro_absrel"]), 4)
        mae = round(float(c_data["pooled_mae"]), 2)
        d1 = round(float(c_data["pooled_delta1"]), 4)
        
        csv_rows.append({
            "model_type": "Single Cue",
            "variant": c_name,
            "display_name": c_name,
            "pooled_absrel": p_abs,
            "macro_absrel": m_abs,
            "delta_macro": 0.0,
            "mae": mae,
            "delta1": d1
        })
        latex_rows.append([
            "Pinhole Cue",
            c_name,
            f"{p_abs:.4f}",
            f"{m_abs:.4f}",
            f"{mae:.2f} m",
            f"{d1*100:.1f}\\%"
        ])
    
    for v_key in ["d", "e", "f0", "f"]:
        v_name, v_data = names_map[v_key]
        p_absrel = v_data["absrel"]
        m_absrel = cs[v_key]["macro"]
        delta1 = v_data["delta1"]
        mae = v_data["mae"]
        
        csv_rows.append({
            "model_type": "Pipeline Variant",
            "variant": v_key,
            "display_name": v_name,
            "pooled_absrel": round(p_absrel, 4),
            "macro_absrel": round(m_absrel, 4),
            "delta_macro": 0.0,
            "mae": round(mae, 2),
            "delta1": round(delta1, 4)
        })
        latex_rows.append([
            "Pipeline Model",
            v_name,
            f"{p_absrel:.4f}",
            f"{m_absrel:.4f}",
            f"{mae:.2f} m",
            f"{delta1*100:.1f}\\%"
        ])
        
    # 2. Key Ablations from abl_b (yolo11s_640) - Bao gồm cả Drop Cue và Drop Group
    abl_records = [r for r in abl_b["records"] if r["model_key"] == "yolo11s_640" and r["category"] in ["drop_cue", "drop_group"]]
    for r in abl_records:
        csv_rows.append({
            "model_type": "Ablation Study",
            "variant": r["ablation_key"],
            "display_name": r["ablation_name"],
            "pooled_absrel": round(r["pooled_absrel"], 4),
            "macro_absrel": round(r["macro_absrel"], 4),
            "delta_pooled": round(r["delta_pooled"], 4),
            "delta_macro": round(r["delta_macro"], 4),
            "ci_lo": round(r["ci_lo"], 4),
            "ci_hi": round(r["ci_hi"], 4),
            "mae": None,
            "delta1": None
        })
        ci_str = f"[{r['ci_lo']:+.4f}, {r['ci_hi']:+.4f}]"
        latex_rows.append([
            "Ablation",
            escape_latex(r["ablation_name"]),
            f"{r['pooled_absrel']:.4f}",
            f"{r['macro_absrel']:.4f}",
            f"{r['delta_pooled']:+.4f} {ci_str}",
            "---"
        ])
        
    df_raw = pd.DataFrame(csv_rows)
    headers = ["Category", "Method / Ablation", "Pooled AbsRel", "Macro AbsRel (12)", "$\\Delta_{\\text{pooled}}$ (vs f) [95\\% CI]", "$\\delta < 1.25$"]
    notes = "Evaluated on Split B out-of-fold (12-fold LODO by drive, $N_{\\text{gt}}=4,776$, $N_{\\text{tp}}=3,523$ for YOLO11s). Single pinhole cues are evaluated on their respective valid subsets; fused geometry and residual models are evaluated on instances with $\\ge 1$ valid cue (common valid support). Covariance weights fit with shrinkage. Paired differences reported against Full Residual (f). Drop Cue $Z_h$ is the only ablation whose 95\\% CI excludes 0 ([+0.0024, +0.0119]); all other ablations span 0."
    write_table_pair("tab_02_geometry_ablation_oof_b", "Geometric Baseline Cues, Covariance Fusion, and Residual Ablation on Split B OOF", "tab:ablation_oof_b", headers, latex_rows, "llrrrr", df_raw, notes)

# ==============================================================================
# 3. BẢNG 3: Bảng Hiệu Năng Chính trên Tập Nghiệm Thu Split T
# ==============================================================================
def export_table_3():
    main_csv_path = REPO_ROOT / "results" / "tables" / "final_eval_main_T.csv"
    boot_csv_path = REPO_ROOT / "results" / "tables" / "final_eval_bootstrap_T.csv"
    common_csv_path = REPO_ROOT / "results" / "tables" / "final_eval_common_T.csv"
    
    main_df = pd.read_csv(main_csv_path)
    boot_df = pd.read_csv(boot_csv_path)
    common_df = pd.read_csv(common_csv_path)
    
    csv_rows = []
    latex_rows = []
    
    det_map = {
        "yolo11s_640": "YOLO11s (640)",
        "yolov8s_640": "YOLOv8s (640)",
        "yolov5su_640": "YOLOv5su (640)"
    }
    
    var_map = {
        "z_w": "Width Cue $Z_w$ (a)",
        "z_h": "Height Cue $Z_h$ (b)",
        "z_g": "Ground Cue $Z_g$ (c*)",
        "z_d": "Fused Geometry $Z_d$ (d*)",
        "z_hat_e": "Direct Depth $Z_e$ (e)",
        "z_hat_f0": "Linear Residual $Z_{f0}$ (f0)",
        "z_hat_f": "Full Residual $\\hat{Z}_f$ (f)"
    }
    
    for det_key, det_name in det_map.items():
        # Lấy bootstrap difference rows cho detector
        fd_row = boot_df[boot_df["comparison"].str.contains(f"{det_key}: (f)_residual vs (d)_fused", regex=False)].iloc[0]
        fe_row = boot_df[boot_df["comparison"].str.contains(f"{det_key}: (f)_residual vs (e)_direct", regex=False)].iloc[0]
        
        fd_ci_str = f"[{fd_row['ci_low']:.4f}, {fd_row['ci_high']:.4f}]"
        fe_ci_str = f"[{fe_row['ci_low']:.4f}, {fe_row['ci_high']:.4f}]"
        fe_est = float(fe_row['estimate'])
        
        for v_key, v_name in var_map.items():
            row = main_df[(main_df["detector"] == det_key) & (main_df["variant"] == v_key)].iloc[0]
            
            p_abs = float(row["absrel_pooled"])
            m_abs = float(row["absrel_macro"])
            m_ge30 = float(row["absrel_macro_ge30"])
            mae = float(row["mae"])
            rmse = float(row["rmse"])
            d1 = float(row["delta1"])
            
            # Cột Paired CI chỉ hiện ở dòng (f) và (e)
            if v_key == "z_hat_f":
                ci_col = f"vs (d): {fd_ci_str}"
                ci_latex = escape_latex(ci_col)
            elif v_key == "z_hat_e":
                ci_col = f"Delta(f - e): {fe_est:+.4f} {fe_ci_str}"
                ci_latex = f"$\\Delta(f - e)$: {fe_est:+.4f} {escape_latex(fe_ci_str)}"
            else:
                ci_col = "---"
                ci_latex = "---"
                
            csv_rows.append({
                "detector": det_key,
                "variant": v_key,
                "display_method": v_name,
                "n_tp": int(row["n_tp"]),
                "recall": round(float(row["recall"]), 4),
                "absrel_pooled": round(p_abs, 4),
                "absrel_macro": round(m_abs, 4),
                "absrel_macro_ge30": round(m_ge30, 4),
                "mae": round(mae, 3),
                "rmse": round(rmse, 3),
                "delta1": round(d1, 4),
                "paired_ci": ci_col
            })
            
            latex_rows.append([
                det_name if v_key == "z_w" else "",
                v_name,
                f"{p_abs:.4f}",
                f"{m_abs:.4f}",
                f"{m_ge30:.4f}",
                f"{mae:.2f}",
                f"{rmse:.2f}",
                f"{d1*100:.1f}\\%",
                ci_latex
            ])
            
    df_raw = pd.DataFrame(csv_rows)
    headers = ["Detector", "Method", "Pooled AbsRel", "Macro (10)", "Macro ($n \\ge 30$)", "MAE (m)", "RMSE (m)", "$\\delta_1$", "Paired 95\\% CI (10 clusters)"]
    notes = "Evaluated on Split T ($N_{\\text{gt}} = 3,212$ Car Hard across 10 drives; single detector training run with seed 42). For YOLO11s, $N_{\\text{tp}} = 2,712$; geometric baseline cues (a--d) evaluate on $n_{\\text{valid}} = 2,676$ detections due to 36 edge fallbacks, whereas Model (f) evaluates on all 2,712 detections. Recall is 84.4\\% (11s), 82.8\\% (v8s), and 83.3\\% (v5su). Common support across all 3 detectors has $N = 2,528$ vehicles where Model (f) AbsRel is 0.0446 (11s), 0.0449 (v8s), and 0.0457 (v5su). Paired Bootstrap CI over 10 drives indicates (f) vs (d) excludes 0, while (f) vs (e) includes 0 (D78)."
    write_table_pair("tab_03_main_benchmark_split_t", "Main Distance Estimation Benchmark on Held-out Split T (Post-hoc Verified v1.1)", "tab:main_benchmark_t", headers, latex_rows, "llrrrrrrr", df_raw, notes)

# ==============================================================================
# 4. BẢNG 4: Phân Tích RQ2 & Tương Quan Sai Số Bounding Box
# ==============================================================================
def export_table_4():
    rq2_csv_path = REPO_ROOT / "results" / "tables" / "final_eval_rq2_correlation.csv"
    rq2_df = pd.read_csv(rq2_csv_path)
    
    csv_rows = []
    latex_rows = []
    
    det_map = {
        "yolo11s_640": "YOLO11s",
        "yolov8s_640": "YOLOv8s",
        "yolov5su_640": "YOLOv5su"
    }
    
    feat_map = {
        "matched_iou": "Bounding Box IoU with GT",
        "confidence": "Detector Confidence Score",
        "delta_y2_px": "Bottom Edge Error $\\Delta y_2$ (px)",
        "abs_delta_y2_px": "Absolute Bottom Error $|\\Delta y_2|$ (px)",
        "delta_y2_rel": "Relative Bottom Error $\\Delta y_2 / h_{\\text{gt}}$",
        "bbox_height": "Bounding Box Height $h$ (px)",
        "bbox_width": "Bounding Box Width $w$ (px)",
        "bbox_area": "Bounding Box Area $w \\cdot h$ (px$^2$)"
    }
    
    for _, row in rq2_df.iterrows():
        f_key = row["detection_feature"]
        if f_key not in feat_map:
            continue
        d_key = row["detector"]
        d_name = det_map.get(d_key, d_key)
        f_name = feat_map[f_key]
        
        pr = float(row["pearson_r"])
        sr = float(row["spearman_rho"])
        sci = str(row["spearman_ci_95"])
        
        csv_rows.append({
            "detector": d_key,
            "feature": f_key,
            "feature_display": f_name,
            "pearson_r": round(pr, 4),
            "spearman_rho": round(sr, 4),
            "spearman_ci_95": sci,
            "n_samples": int(row["n_samples"])
        })
        
        latex_rows.append([
            d_name,
            f_name,
            f"{pr:+.4f}",
            f"{sr:+.4f}",
            escape_latex(sci),
            f"{int(row['n_samples']):,}"
        ])
        
    df_raw = pd.DataFrame(csv_rows)
    headers = ["Detector", "Bbox Metric", "Pearson $r$", "Spearman $\\rho$", "95\\% Bootstrap CI (10 clusters)", "$n$"]
    notes = "Correlations evaluated against AbsRel error on Split T True Positives ($N=2,712$ for YOLO11s, detector seed 42). Spearman $\\rho$ is the primary robust metric. 23/24 CI configurations include 0 at the 10-cluster drive level, indicating distance error is largely decoupled from 2D bounding box jitter."
    write_table_pair("tab_04_rq2_detector_correlation", "RQ2: Correlation between Monocular Ranging Error and 2D Detection Quality", "tab:rq2_correlation", headers, latex_rows, "llrrrc", df_raw, notes)

# ==============================================================================
# 5. BẢNG 5: Định Lượng Bất Định & Độ Phủ Conformal trên Split T
# ==============================================================================
def export_table_5():
    t_json_path = REPO_ROOT / "results" / "tables" / "final_eval_T.json"
    with open(t_json_path, "r", encoding="utf-8") as f:
        t_data = json.load(f)
        
    csv_rows = []
    latex_rows = []
    
    det_map = {
        "yolo11s_640": "YOLO11s",
        "yolov8s_640": "YOLOv8s",
        "yolov5su_640": "YOLOv5su"
    }
    
    for det_key, det_name in det_map.items():
        m = t_data[det_key]["metrics"]
        
        variants = [
            ("Standard CQR (Primary)", m["standard_cqr"]),
            ("Split Conformal (Baseline)", m["split_conformal"]),
            ("Mondrian CQR (Distance Bins)", m["mondrian_cqr"])
        ]
        
        for v_name, v_data in variants:
            p_cov = float(v_data["pooled_coverage"])
            m_cov = float(v_data.get("macro_coverage", 0.0))
            if "macro_coverage_ge30" in v_data:
                m_ge30 = float(v_data["macro_coverage_ge30"])
                m_ge30_str = f"{m_ge30*100:.1f}\\%"
            else:
                m_ge30 = None
                m_ge30_str = "---"
            w_ratio = float(v_data["mean_width_ratio"])
            winkler = float(v_data.get("mean_winkler", 0.0))
            crossings = int(v_data.get("n_crossings", 0))
            
            csv_rows.append({
                "detector": det_key,
                "variant": v_name,
                "pooled_coverage": round(p_cov, 4),
                "macro_coverage": round(m_cov, 4),
                "macro_coverage_ge30": round(m_ge30, 4) if m_ge30 is not None else None,
                "mean_width_ratio": round(w_ratio, 3),
                "mean_winkler": round(winkler, 4) if winkler > 0 else None,
                "crossing_count": crossings
            })
            
            latex_rows.append([
                det_name if "Standard" in v_name else "",
                escape_latex(v_name),
                f"{p_cov*100:.1f}\\%",
                f"{m_cov*100:.1f}\\%",
                m_ge30_str,
                f"{w_ratio:.3f}x",
                f"{winkler:.4f}" if winkler > 0 else "---",
                str(crossings)
            ])
            
    df_raw = pd.DataFrame(csv_rows)
    headers = ["Detector", "Conformal Variant", "Pooled Cov", "Macro (10)", "Macro ($n \\ge 30$)", "Mean Width Ratio", "Winkler Score", "Crossings"]
    notes = "Target nominal coverage is $1 - \\alpha = 90.0\\%$. Calibrated on Split C ($N_{\\text{gt}}=1,826$, $n_{\\text{tp}}=1,489$ for YOLO11s, 10 drives). Evaluated on Split T ($N_{\\text{gt}}=3,212$, $N_{\\text{tp}}=2,712$ for YOLO11s, detector seed 42). Standard CQR yields conservative over-coverage (96.4\\%--97.1\\%) with mean width ratio 1.32$\\times$--1.35$\\times$ pooled (1.45$\\times$ in 0--10m band) due to calibration set difficulty distribution (D79, D87). Zero crossing observed across all models."
    write_table_pair("tab_05_conformal_coverage_t", "Uncertainty Quantification and Conformal Coverage Evaluation on Split T", "tab:conformal_coverage_t", headers, latex_rows, "llrrrrrr", df_raw, notes)

# ==============================================================================
# 6. BẢNG 6: Độ Phủ Có Điều Kiện theo Miền Vận Hành ODD trên Split T
# ==============================================================================
def export_table_6():
    cond_path = REPO_ROOT / "results" / "tables" / "coverage_conditional_T.json"
    with open(cond_path, "r", encoding="utf-8") as f:
        cond_data = json.load(f)
        
    # Trích xuất cho detector chính: yolo11s_640
    y11 = cond_data["yolo11s_640"]["categories"]
    
    csv_rows = []
    latex_rows = []
    
    cat_order = [
        ("Distance Bins $\\hat{Z}$ (m)", "z_hat_prospective"),
        ("Ground Truth Distance $Z$ (m)", "z_gt_retrospective"),
        ("Truncation & Edge Effects", "truncation_and_edges"),
        ("KITTI Occlusion Level", "occlusion"),
        ("Vehicle Viewing Angle $\\theta$", "viewing_angle_theta"),
        ("KITTI Difficulty Filter", "difficulty"),
        ("Fallback Pattern 000", "fallback_pattern_000")
    ]
    
    for cat_title, cat_key in cat_order:
        subgroups = y11.get(cat_key, [])
        first = True
        for sg in subgroups:
            if "cqr" not in sg:
                continue
            sg_name = sg.get("subgroup", "Unknown")
            ntp = int(sg.get("n_tp", 0))
            nfn = sg.get("n_fn")
            ngt = sg.get("n_gt")
            rec = sg.get("recall")
            
            cqr_cov = float(sg["cqr"]["coverage"])
            cqr_w = float(sg["cqr"]["mean_width"])
            sc_cov = float(sg["sc"]["coverage"])
            mon_cov = float(sg["mondrian"]["coverage"])
            
            # Cờ mẫu nhỏ D54
            low_n_flag = "*" if ntp < 100 else ""
            
            rec_str = f"{rec*100:.1f}\\%" if rec is not None else "---"
            ngt_str = f"{int(ngt):,}" if ngt is not None else "---"
            nfn_str = f"{int(nfn):,}" if nfn is not None else "---"
            
            csv_rows.append({
                "category": cat_key,
                "category_title": cat_title,
                "subgroup": sg_name,
                "n_tp": ntp,
                "n_fn": nfn,
                "n_gt": ngt,
                "recall": rec,
                "cqr_coverage": round(cqr_cov, 4),
                "sc_coverage": round(sc_cov, 4),
                "mondrian_coverage": round(mon_cov, 4),
                "mean_width_ratio": round(cqr_w, 3),
                "is_low_sample": ntp < 100
            })
            
            latex_rows.append([
                cat_title if first else "",
                escape_latex(str(sg_name)),
                ngt_str,
                f"{ntp}{low_n_flag}",
                nfn_str,
                rec_str,
                f"{cqr_cov*100:.1f}\\%",
                f"{sc_cov*100:.1f}\\%",
                f"{mon_cov*100:.1f}\\%",
                f"{cqr_w:.3f}x"
            ])
            first = False
            
    df_raw = pd.DataFrame(csv_rows)
    headers = ["Operational Domain (ODD)", "Subset", "$N_{\\text{gt}}$", "$n_{\\text{TP}}$", "$n_{\\text{FN}}$", "Recall", "CQR Cov", "SC Cov", "Mondrian Cov", "CQR Width"]
    notes = "Evaluated on YOLO11s across Split T. Target nominal coverage is 90.0\\%. Asterisk (*) denotes small sample size ($n_{\\text{TP}} < 100$). Per Decision D91, Recall is reported only for ground-truth subsets where False Negatives are well-defined. Fallback pattern 000 group ($n=36$) achieves 77.8\\% coverage."
    write_table_pair("tab_06_conditional_coverage_odd", "Conditional Conformal Coverage across Operational Design Domains (ODD) on Split T", "tab:conditional_coverage_odd", headers, latex_rows, "llrrrrrrrr", df_raw, notes)

def export_table_7():
    """Bảng 7: Benchmark Độ trễ Tier 1 Real-time & Kiểm tra Parity (D94, D98, D100, D104)."""
    src_json = REPO_ROOT / "results" / "tables" / "latency_tier1.json"
    if not src_json.exists():
        print("Warning: latency_tier1.json not found, skipping Table 7.")
        return
        
    with open(src_json, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    detectors = data.get("detectors", {})
    # Thứ tự trình bày chuẩn
    detector_order = [
        ("yolo11s_640", "YOLO11s (640)"),
        ("yolov8s_640", "YOLOv8s (640)"),
        ("yolov5su_640", "YOLOv5su (640)"),
    ]
    
    csv_rows = []
    latex_rows = []
    
    for key, name in detector_order:
        if key not in detectors:
            continue
        d_info = detectors[key]
        lat = d_info.get("latency", {})
        par = d_info.get("parity", {})
        
        pre_gpu = lat.get("preprocess_gpu", {}).get("median_ms", 0.0)
        det_gpu = lat.get("detector_gpu_fp16", {}).get("median_ms", 0.0)
        post_gpu = lat.get("postprocess_gpu", {}).get("median_ms", 0.0)
        geom_gpu = lat.get("geometry_gpu", {}).get("median_ms", 0.0)
        res_gpu = lat.get("residual_gpu", {}).get("median_ms", 0.0)
        cqr_gpu = lat.get("cqr_gpu", {}).get("median_ms", 0.0)
        
        tot_gpu_med = lat.get("total_pipeline_gpu", {}).get("median_ms", 0.0)
        tot_gpu_p95 = lat.get("total_pipeline_gpu", {}).get("p95_ms", 0.0)
        tot_gpu_fps = lat.get("total_pipeline_gpu", {}).get("fps_median", 1000.0 / tot_gpu_med if tot_gpu_med > 0 else 0.0)
        
        tot_cpu_med = lat.get("total_pipeline_cpu", {}).get("median_ms", 0.0)
        tot_cpu_p95 = lat.get("total_pipeline_cpu", {}).get("p95_ms", 0.0)
        tot_cpu_fps = lat.get("total_pipeline_cpu", {}).get("fps_median", 1000.0 / tot_cpu_med if tot_cpu_med > 0 else 0.0)
        
        count_ratio = par.get("count_ratio", 0.0)
        iou_rate = par.get("high_iou_match_rate", 0.0)
        
        csv_rows.append({
            "detector": key,
            "display_name": name,
            "preprocess_gpu_ms": round(pre_gpu, 2),
            "detector_forward_gpu_ms": round(det_gpu, 2),
            "postprocess_gpu_ms": round(post_gpu, 2),
            "geometry_gpu_ms": round(geom_gpu, 2),
            "residual_gpu_ms": round(res_gpu, 2),
            "cqr_gpu_ms": round(cqr_gpu, 2),
            "total_gpu_median_ms": round(tot_gpu_med, 2),
            "total_gpu_p95_ms": round(tot_gpu_p95, 2),
            "total_gpu_fps": round(tot_gpu_fps, 1),
            "total_cpu_median_ms": round(tot_cpu_med, 2),
            "total_cpu_p95_ms": round(tot_cpu_p95, 2),
            "total_cpu_fps": round(tot_cpu_fps, 1),
            "parity_count_ratio": round(count_ratio, 4),
            "parity_high_iou_match_rate": round(iou_rate, 4),
            "status": "PRELIMINARY-v2"
        })
        
        latex_rows.append([
            name,
            f"{pre_gpu:.1f}",
            f"{det_gpu:.1f}",
            f"{post_gpu:.2f}",
            f"{geom_gpu:.2f}",
            f"{res_gpu:.2f}",
            f"{cqr_gpu:.2f}",
            f"{tot_gpu_med:.1f} / {tot_gpu_p95:.1f}",
            f"{tot_gpu_fps:.1f}",
            f"{tot_cpu_med:.1f} / {tot_cpu_p95:.1f}",
            f"{tot_cpu_fps:.1f}",
            f"{count_ratio:.3f}",
            f"{iou_rate*100:.1f}\\%"
        ])
        
    df_raw = pd.DataFrame(csv_rows)
    headers = [
        "Detector", "Pre (GPU)", "Det (GPU)", "Post (GPU)", "Geom", "Resid", "CQR",
        "GPU Total (Med/P95)", "GPU FPS", "CPU Total (Med/P95)", "CPU FPS", "Parity Count", "Parity IoU"
    ]
    notes = "\\textbf{Status: PRELIMINARY-v2.} Evaluated on 200 in-memory frames of Split B with 40 warmup iterations on RTX 5060 Laptop GPU (FP16 CUDA) and AMD CPU (ONNX Runtime FP32, 4 threads). Per Decision D98, no detector throughput ranking is claimed. Count parity reaches [0.95, 1.05]; IoU match rate $< 0.95$ due to static $640 \\times 640$ padding vs dynamic $640 \\times 224$ letterbox (D99, D100, D104). Post-detector stages (geometry + residual + CQR) add only $\\approx 1.35$ ms total ($< 4.2\\%$ of GPU pipeline)."
    write_table_pair("tab_07_latency_tier1_realtime", "Tier 1 End-to-End Real-Time Latency Breakdown and PyTorch/ONNX Parity Verification", "tab:latency_tier1_realtime", headers, latex_rows, "lrrrrrrrrrrrr", df_raw, notes)

def main():
    print("Exporting publication-ready tables to results/tables/final/...")
    export_table_1()
    export_table_2()
    export_table_3()
    export_table_4()
    export_table_5()
    export_table_6()
    export_table_7()
    print("All 7 publication tables successfully exported!")

if __name__ == "__main__":
    main()
